# Habilita la consola visual
spring.h2.console.enabled=true

# Nombre de la base de datos en memoria
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Hace que Hibernate cree las tablas automáticamente al arrancar
spring.jpa.hibernate.ddl-auto=update



# Apaga los logs de Spring (solo muestra Errores)
logging.level.root=ERROR
# Apaga el logo de Spring al inicio
spring.main.banner-mode=off


# Permite que Hibernate cree la tabla y luego se ejecute el data.sql
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always