INSERT INTO TAREA (descripcion, completada) VALUES ('Comprar pan artesano', false);
INSERT INTO TAREA (descripcion, completada) VALUES ('Lavar el coche de la empresa', true);
INSERT INTO TAREA (descripcion, completada) VALUES ('Estudiar Spring Data JPA', false);
INSERT INTO TAREA (descripcion, completada) VALUES ('Preparar la cena con pan de ajo', false);
INSERT INTO TAREA (descripcion, completada) VALUES ('Hacer ejercicio en el gimnasio', true);
INSERT INTO TAREA (descripcion, completada) VALUES ('Llamar a los clientes pendientes', false);
INSERT INTO TAREA (descripcion, completada) VALUES ('Lavar el teclado del ordenador', true);
INSERT INTO TAREA (descripcion, completada) VALUES ('Actualizar el sistema operativo', false);
INSERT INTO TAREA (descripcion, completada) VALUES ('Comprar leche y cereales', true);
INSERT INTO TAREA (descripcion, completada) VALUES ('Revisar correos electrónicos', false);
INSERT INTO TAREA (descripcion, completada) VALUES ('Pagar la factura del gas', true);
INSERT INTO TAREA (descripcion, completada) VALUES ('Configurar el repositorio de Git', false);
INSERT INTO TAREA (descripcion, completada) VALUES ('Pasear al perro por el parque', true);
INSERT INTO TAREA (descripcion, completada) VALUES ('Leer un capítulo de Java moderno', false);
INSERT INTO TAREA (descripcion, completada) VALUES ('Organizar la estantería de libros', false);
INSERT INTO TAREA (descripcion, completada) VALUES ('Comprar moldes para pan', true);
INSERT INTO TAREA (descripcion, completada) VALUES ('Enviar informe semanal', true);
INSERT INTO TAREA (descripcion, completada) VALUES ('Arreglar la persiana del salón', false);
INSERT INTO TAREA (descripcion, completada) VALUES ('Cargar la batería de la cámara', true);
INSERT INTO TAREA (descripcion, completada) VALUES ('Planear las vacaciones de verano', false);